admin11/admin11/urls.py
from django.contrib.auth.views import LoginView

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from landing.views import *
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#handler404 = pageNotFound

admin11/index/urls.py
from django.urls import path
from .views import *

urlpatterns = [    
    path('',title),
]

# hendler404 = pageNotFound

admin11/landing/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

from .views import *

app_name = 'landing'


urlpatterns = [    
    path('',LandingHome.as_view(),name='home'),
    path('post/',postOut,name='postform'),

    path('login/',LoginUser.as_view(),name='login'),
    path('signup/',RegisterUser.as_view(),name='signup'),
    path('logout/',logout_user,name='logout'),

    path('dashboard/',DashboardPage.as_view(),name='dashboard'),
    path('edit/',EditMode.as_view(),name='edit'),
    path('edit/block/<int:id_block>/',EditBlock.as_view(),name='edit_block'),
    path('edit/published/<int:id_block>/',EditModeDisableBlock,name='published'),
    path('edit/save/<int:id_block>/',EditModeSaveBlock,name='edit_save'),
    path('edit/add/',EditModeAddBlock,name='add_block'),
    path('edit/del/<int:id_block>/',EditModeDelBlock,name='del_block'),
    path('sorting/',SortingHome.as_view(),name='sorting'),
   
    path('sort/',sort_blocks),

    path('orders/',OrderPage.as_view(),name='order'),
    path('orders/<int:order_id>/',getOrderOut,name='order_id'),
    path('orders/edit/<int:order_id>/',OrderEdit,name='order_id_edit'),
    path('orders/del/<int:order_id>/',OrderDel,name='order_id_del'),

    path('users/',UsersPage.as_view(),name='users'),

    path('files/',FilesPage.as_view(),name='files'),
    path('files/upload/',UploadFiles,name='upload_files'),
    path('files/del/<int:id_image>/',DelFileDate,name='del_files'),
    path('files/get_file/<int:id_file>/',GetFile,name='get_file'),
    path('files/get_files/',GetFiles,name='get_files'),

    path('profile/',ProfilePage.as_view(),name='profile'),

    path('settings/',SettingsPage.as_view(),name='settings')

    #path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
]

#hendler404 = pageNotFound

admin11/landing/views.py
from django.http import HttpResponse,HttpResponseNotFound

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import logout

from django.urls import reverse_lazy,reverse
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import ListView, DetailView, CreateView

from django.core.files.storage import FileSystemStorage
from django.conf import settings

from .models import *
from .utils import *
from .forms import *
#from .urls import *

import json
from datetime import datetime
from bs4 import BeautifulSoup
import os
import subprocess
from datetime import date
import urllib


class LandingHome(ListView):
    model = landing
    template_name = 'landing/index.html'
    context_object_name ='all'
    #extra_context = {'title':'ООО Сисадмин — Обслуживание информационых систем'}

    def get_context_data(self,*, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        blocks = landing.objects.filter(is_published=True).order_by('order')
        new_dictData = {}

        context['title'] = 'ООО Сисадмин — Обслуживание информационых систем'

        # for i in range(len(blocks)):
        #     #print(blocks[i].title)

        #     settings_block = blocks.filter(title=blocks[i].title)[0]
        #     if settings_block.content != '':
        #         if settings_block.type_block != 'html':
        #             context[blocks[i].title] = json.loads(settings_block.content)
        #         else:
        #             context[blocks[i].title] = settings_block.content
        #     else:
        #         context[blocks[i].title] = ''
        
        # print(self.request.user.is_authenticated)
        num_visits=self.request.session.get('num_visits', 0)
        self.request.session['num_visits'] = num_visits+1
        print(str(num_visits)+' <---')

        if not self.request.user.is_authenticated:
            visitor = visitors(
            ip=self.request.META.get('REMOTE_ADDR'),
            browser=self.request.META.get('HTTP_USER_AGENT'),    
            time_out=self.request.session.get('num_visits', 0)    
            )
            visitor.save()

        return context

    def get_queryset(self):
        return landing.objects.filter(is_published=True).order_by('order')

class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'accounts/darkpan/signup.html'
    success_url = reverse_lazy('landing:login')
    
    def get_context_data(self, *, object_list=None, **kwargs) :
        context = super () .get_context_data(**kwargs)
        c_def = self.get_user_context (title="Регистрация")

        return dict(list(context.items ()) + list(c_def.items ()))

class LoginUser(DataMixin, LoginView):
    form_class = AuthenticationForm
    template_name = 'accounts/darkpan/signin.html'

    def get_context_data(self, *, object_list=None, **kwargs) :
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")

        return dict(list (context.items ()) + list(c_def.items ()))

    def get_success_url(self):
        return reverse_lazy('landing:dashboard')
        #return redirect('/')

def logout_user(request):
    logout(request)
    return redirect('landing:login')

# Create your views here.
def title(request):
    # key = request.GLOBAL
    # print(key)
    #return HttpResponse('Привет мир ')

    settings_header = landing.objects.filter(title='header')

    blocks = landing.objects.all()

    header = json.loads(blocks.filter(title='header')[0].content)

    #print(blocks[0].title)

    new_dictData = {}

    for i in range(len(blocks)):
        #print(blocks[i].title)

        settings_block = blocks.filter(title=blocks[i].title)[0].content
        new_dictData[blocks[i].title] = json.loads(settings_block)

    #print(new_dictData['hero'])    

    return render(request,'landing/index.html',new_dictData)

class SortingHome(LoginRequiredMixin,ListView):
    model = landing
    template_name = 'accounts/sorting.html'
    context_object_name ='items'
    ordering = ['order']
    login_url = '/admin/'
    #raise_exception = True

class DashboardPage(LoginRequiredMixin,DataMixin,ListView):
    model = landing
    template_name = 'accounts/darkpan/dashboard.html'
    context_object_name ='items'
    ordering = ['order']
    login_url = '/admin/'

    def get_context_data(self,*, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        print(self.request.user)
        context['user'] = self.request.user
        context['orders'] = bids.objects.order_by("-id")[0:5]
        context['orders_count'] =bids.objects.count()
        context['visitors_count'] = visitors.objects.filter(time_out='1').count()
        context['reload_page_count'] = visitors.objects.count()
        context['ip_count'] = visitors.objects.values('ip').distinct().count()
        c_def = self.get_user_context(title="Панель упровления",selected="landing:dashboard")
        context = dict(list(context.items())+list(c_def.items()))
        return context

class ProfilePage(LoginRequiredMixin,DataMixin,ListView):
    model = landing
    template_name = 'accounts/darkpan/profile.html'
    context_object_name ='items'
    login_url = '/admin/'

    def get_context_data(self,*, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['orders'] = bids.objects.order_by("-id")
        context['orders_count'] =bids.objects.count()
        c_def = self.get_user_context(title="Профиль",selected="landing:profile")
        context = dict(list(context.items())+list(c_def.items()))
        return context

class SettingsPage(LoginRequiredMixin,DataMixin,ListView):
    model = landing
    template_name = 'accounts/darkpan/settings.html'
    context_object_name ='items'
    login_url = '/admin/'

    def get_context_data(self,*, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['orders'] = bids.objects.order_by("-id")
        context['orders_count'] =bids.objects.count()
        c_def = self.get_user_context(title="Настройки",selected="landing:settings")
        context = dict(list(context.items())+list(c_def.items()))
        return context
    
class EditMode(LoginRequiredMixin,DataMixin,ListView):
    model = landing
    template_name = 'accounts/darkpan/edit_mode.html'
    context_object_name ='all'    
    login_url = '/admin/'

    def get_context_data(self,*, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        #blocks = landing.objects.all().order_by('order')
        new_dictData = {}

        context['title'] = 'ООО Сисадмин — Обслуживание информационых систем'
        context['edit_mode']='True'
        #context['add_block']=['header','html','footer']
        context['add_block'] = []
           

        for item in get_template_file_name():
            context['add_block'].append(get_template_info(item))

        
        
        return context

    def get_queryset(self):
        return landing.objects.all().order_by('order')

@login_required
def EditModeAddBlock(request):

    print(request.POST.getlist('NameBlock')[0])
    print(request.POST.getlist('TypeBlock')[0])

    info = get_template_info(request.POST.getlist('TypeBlock')[0])

    new_block = landing(
            title = request.POST.getlist('TypeBlock')[0].replace(' \n',''),
            name = request.POST.getlist('NameBlock')[0],
            content = info['base'],
            type_block = info['type_base'],
               
            )
    new_block.save()

    #return redirect('/edit/#'+block.title)
    return redirect('landing:edit')

@login_required
def EditModeDisableBlock(request,id_block):

    block = landing.objects.get(id = id_block)
    #print(block.)

    if block.is_published == False:
        block.is_published = True
    else:    
        block.is_published = False

    block.save()

    #return redirect('/edit/#'+block.title)
    return HttpResponse('Good')

@login_required
def EditModeSaveBlock(request,id_block):
    block = landing.objects.get(id=id_block)
    
    if request.POST.getlist('content'):
        block.content = request.POST.getlist('content')[0]
        block.save()
    else:
        #print('Ключа нет')
        #print(request.POST)
        html = str(request.POST.getlist('content_admin'))
        # print('')
        # print(html)
        # print('')
        soup = BeautifulSoup('<div name="main">'+html+'</div>','html.parser')
        json_obj = parse_element(soup.find('div'),0,'main')
        
        out2 = str(json_obj).replace('"', "'")
        #out2 = out2.replace('"', "'")

        #print(out2.replace('\\', "  ").replace("'", '"').replace('  "', "'"))

        block.content = out2.replace('\\', "  ").replace("'", '"').replace('  "', "'")
        block.content = block.content.replace('  ','')
        block.content = str(json.dumps(json.loads(block.content), indent=4))
        print(str(json.dumps(json.loads(block.content), indent=4)))
        block.save()

        #print(request.POST.getlist('content_admin'))

        # html = str(request.POST.getlist('content_admin'))       
        # soup = BeautifulSoup('<div>'+html+'</div>','html.parser')        

        # json_obj = parse_element_new(soup.find('div'))
        # print(json_obj)

        

    print(request.POST.getlist('content'))
    return redirect('landing:edit')

@login_required
def EditModeDelBlock(request,id_block):
    record = landing.objects.get(id=id_block)
    record.delete()

    return redirect('landing:edit')

@login_required
def sort_blocks(request):    

    # print(arr_out)

admin11/landing/templates/accounts/darkpan/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet"> 
    
    <!-- Icon Font Stylesheet -->
    <!-- <link rel="stylesheet" href="https://kit.fontawesome.com/7b04adc9a1.css" crossorigin="anonymous"> -->
    <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet"> -->

    <!-- Libraries Stylesheet -->
    <link href="{% static 'accounts/'%}lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="{% static 'accounts/'%}lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'accounts/'%}css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'accounts/'%}css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->       


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="{% url 'landing:home' %}" class="d-flex align-items-center navbar-brand mx-4 mb-3 w-100">
                    <img src="{% static 'accounts/'%}img/logo.svg">
                </a>
                <div class="d-flex align-items-center ms-4 mb-4 mt-4 w-100">
                    <div class="position-relative">
                        
                       <img class="rounded-circle" src="/media/files/2023/05/02/angry.png" alt="" style="width: 40px; height: 40px;"> 
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{ user.email }}</h6>
                        {% if user.is_superuser %}
                            <span>admin</span>
                        {% else %}
                            <span>no admin</span>
                        {% endif %}
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    {% for item in menu_admin %}
                        {% if item.url_name == selected %}
                            <a href="{% url item.url_name %}" class="nav-item nav-link active"><i class="fa {{ item.icon }} me-2"></i>{{ item.title }}</a>
                        {% else %}
                            <a href="{% url item.url_name %}" class="nav-item nav-link"><i class="fa {{ item.icon }} me-2"></i>{{ item.title }}</a>
                        {% endif %}
                        

                    {% endfor %}
                    <!-- <a href="{% url 'landing:dashboard' %}" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <a href="{% url 'landing:edit' %}" class="nav-item nav-link"><i class="fa fa-edit me-2"></i>Режим ред.</a>
                    <a href="{% url 'landing:order' %}" class="nav-item nav-link"><i class="fa fa-shopping-basket me-2"></i>Заявки</a>
                    <a href="{% url 'landing:users' %}" class="nav-item nav-link"><i class="fa fa-users me-2"></i>Посетители</a>
                    <a href="{% url 'landing:files' %}" class="nav-item nav-link"><i class="fa fa-folder-open me-2"></i>Файлы</a> -->

                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content ">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <!-- <form class="d-none d-md-flex ms-4">
                    <input class="form-control bg-dark border-0" type="search" placeholder="Search">
                </form> -->
                <div class="navbar-nav align-items-center ms-auto">
                    <!-- <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-envelope me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Message</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificatin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div> -->
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <!-- <img class="rounded-circle me-lg-2" src="img/user.jpg" alt="" style="width: 40px; height: 40px;"> -->
                            <span class="d-none d-lg-inline-flex">{{ user.email }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="{% url 'landing:dashboard' %}" class="dropdown-item">Панель упровления</a>
                            <a href="{% url 'landing:profile' %}" class="dropdown-item">Профиль</a>
                            <a href="{% url 'landing:logout' %}" class="dropdown-item">Выход</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
        
            {% block content %}
            {% endblock %}
            
            <!-- Footer Start -->
            <div class="mt-auto position-sticky top-100" style="margin-top: 117px !important;">
                <div class="container-fluid pt-4 px-4 position-absolute bottom-0"  >
                    <div class="bg-secondary rounded-top p-4" >
                        <div class="row" >
                            <div class="col-12 col-sm-6 text-center text-sm-start">
                                &copy; <a href="#">Larding</a>, All Right Reserved. 
                            </div>
                            <div class="col-12 col-sm-6 text-center text-sm-end">
                                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                                Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                                <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <!-- <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a> -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://kit.fontawesome.com/7b04adc9a1.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'accounts/'%}lib/chart/chart.min.js"></script>
    <script src="{% static 'accounts/'%}lib/easing/easing.min.js"></script>
    <script src="{% static 'accounts/'%}lib/waypoints/waypoints.min.js"></script>
    <script src="{% static 'accounts/'%}lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="{% static 'accounts/'%}lib/tempusdominus/js/moment.min.js"></script>
    <script src="{% static 'accounts/'%}lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="{% static 'accounts/'%}lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="{% static 'accounts/'%}js/main.js"></script>
    <script src="{% static 'accounts/'%}js/admin.js"></script>
</body>

</html>

admin11/landing/templates/accounts/darkpan/settings.html
{% extends "accounts/darkpan/base.html" %}

{% block content %}

            <!-- Модальное окно загрузки -->           
            <div class="modal fade" id="UploadModal" tabindex="-1" aria-labelledby="UploadModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
                    <div class="modal-content bg-secondary rounded ">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="UploadModalLabel">Загрузить файлы</h1>
                            <button type="button" class="btn btn-square btn-secondary m-2" data-bs-dismiss="modal" aria-label="Close">
                                <i class="fa fa-close" aria-hidden="true"></i>
                            </button>
                        </div>
                        <form action="{% url 'landing:upload_files' %}" method="POST" enctype="multipart/form-data" id="upload-form">
                            <div class="modal-body">

                                <div id="file-dropzone">
                                    <p>Поместите файлы сюда или нажмите, чтобы выбрать файлы.</p>
                                    <input style="display:none;" type="file" name="files" multiple="true" id="file-input">
                                    <div id="selected-files"></div>
                                    <button id="file-input-button" class="btn btn-outline-primary m-2" type="button">Выбрать файлы</button>                                    
                                </div>
                            </div>
                            <div class="modal-footer">
                                {% csrf_token %}
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Загрузить</button>
                            </div>
                        </form>                        
                    </div>
                </div>
            </div>            

            <!-- Модальное окно загрузки -->

            <!-- Модальное окно детали -->

            <div class="modal fade" id="DetailModal" tabindex="-1" aria-labelledby="DetailModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
                    <div class="modal-content bg-secondary rounded ">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="DetailModalLabel">Имя файла</h1>
                            <button type="button" class="btn btn-square btn-secondary m-2"  data-bs-dismiss="modal" aria-label="Close">
                                <i class="fa fa-close" aria-hidden="true"></i>
                            </button>
                        </div>
                       
                        <div class="modal-body">                            
                        </div>

                        <div class="modal-footer">                            
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                                               
                    </div>
                </div>
            </div>            

            <!-- Модальное окно детали -->

            

            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-left rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Настройки</h6>                        
                    </div> 
                    <div class="row">                  
                        <div class="mb-3">
                            <label class="form-label">Тема:</label>
                            <select class="form-select mb-3" aria-label="Default select example">
                                <option selected="">root</option>
                                <option value="1">Администратор</option>
                                <option value="2">Контент менеджер</option>
                                <option value="3">Продажник</option>
                            </select>
                        </div>
                           
                    </div> 
                </div>
            </div>
            <!-- Recent Sales End -->


            

{% endblock %}